apiVersion: apps/v1
kind: Deployment
metadata:
  name: diskreader-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diskreader
  template:
    metadata:
      labels:
        app: diskreader
    spec:
      containers:
      - name: diskreader
        image: fedora:26
        command: ["/bin/sh", "-c"]
        args: [ "tail -f /dev/null" ]
        volumeDevices:
        - name: diskreader-pvc
          devicePath: /dev/xvda
      volumes:
      - name: diskreader-pvc
        persistentVolumeClaim:
          claimName: diskreader-pvc
      imagePullSecrets:
      - name: my-registry-secret    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: diskreader-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName:  default-storageclass
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  dataSource:
    name: snapshot1
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io

